# Generated by Django 3.1.2 on 2021-02-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20210202_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
